use std::{collections::HashMap, env, fs, process::Command, sync::{Arc, Mutex}, time::{Duration, SystemTime, UNIX_EPOCH}};
use axum::{body::Bytes, extract::{Path, State}, http::{HeaderMap, StatusCode}, response::Html, routing::{get, post}, Json, Router};
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};
use tokio::{sync::RwLock, task::JoinSet, time::sleep};

// Recompile the embedded interface whenever this server is rebuilt.
const APP_HTML: &str = include_str!("../static/index.html");

#[derive(Clone)] struct App { db: Arc<Mutex<Connection>>, model: Arc<RwLock<Model>> }
#[derive(Clone, Serialize, Deserialize)] struct Node { id:String, parent:Option<String>, name:String, kind:String, instruction:String, categories:Vec<String>, when:String, enabled:bool, order:u32 }
#[derive(Clone, Serialize, Deserialize)] struct Chunk { index:usize, text:String, tokens:usize, pages:String }
#[derive(Clone, Serialize, Deserialize)] struct ResultRow { chunk:usize, node:String, state:String, answer:String, reason:String, evidence:String, evidence_found:bool, duration_ms:u64, attempts:u8, error:String }
#[derive(Clone, Serialize, Deserialize)] struct Execution { state:String, current:usize, finished:usize, limit:usize, mode:String, event:String }
#[derive(Clone, Serialize, Deserialize)] struct Model { document:String, chunks:Vec<Chunk>, nodes:Vec<Node>, results:Vec<ResultRow>, execution:Execution }
#[derive(Deserialize)] struct NodesInput { nodes:Vec<Node> }
#[derive(Serialize)] struct ErrorBody { error:String }

fn example_nodes() -> Vec<Node> { vec![
 Node{id:"obligation".into(),parent:None,name:"Existe uma obrigação neste trecho?".into(),kind:"binary".into(),instruction:"Identifique se o trecho contém uma obrigação. Responda sim ou não, justificativa curta e citação literal.".into(),categories:vec![],when:"always".into(),enabled:true,order:1},
 Node{id:"type".into(),parent:Some("obligation".into()),name:"Qual é o tipo de obrigação?".into(),kind:"classification".into(),instruction:"Classifique a obrigação identificada.".into(),categories:vec!["financeira".into(),"operacional".into(),"documental".into(),"outra".into()],when:"yes".into(),enabled:true,order:1},
 Node{id:"deadline".into(),parent:Some("obligation".into()),name:"Existe prazo explícito?".into(),kind:"binary".into(),instruction:"Identifique prazo explícito.".into(),categories:vec![],when:"yes".into(),enabled:true,order:2},
 Node{id:"owner".into(),parent:Some("obligation".into()),name:"Existe responsável explicitamente identificado?".into(),kind:"binary".into(),instruction:"Identifique responsável explícito.".into(),categories:vec![],when:"yes".into(),enabled:true,order:3},
 Node{id:"deadline_type".into(),parent:Some("deadline".into()),name:"Qual é o tipo de prazo?".into(),kind:"classification".into(),instruction:"Classifique o prazo.".into(),categories:vec!["data fixa".into(),"período relativo".into(),"recorrente".into(),"outro".into()],when:"yes".into(),enabled:true,order:1},
]}
fn edital_battery() -> Vec<Node> {
    let temas = [
        ("identificação do certame", "número, modalidade e órgão promotor"), ("objeto", "bens ou direitos colocados em leilão"),
        ("lotes", "quantidade, composição e individualização dos lotes"), ("exposição", "local, período e condições de visitação"),
        ("datas", "datas de abertura, encerramento e sessões"), ("horários", "horários e fuso de cada etapa"),
        ("local do leilão", "canal presencial, eletrônico ou híbrido"), ("habilitação", "documentos e requisitos do participante"),
        ("impedimentos", "vedações de participação"), ("cadastro", "procedimento e prazo de credenciamento"),
        ("lances", "forma, incrementos e validade dos lances"), ("preço mínimo", "valor mínimo ou critério de aceitação"),
        ("pagamento", "forma, prazo e comprovação de pagamento"), ("comissão", "remuneração e responsabilidade pelo pagamento ao leiloeiro"),
        ("tributos", "impostos, taxas e encargos incidentes"), ("retirada", "prazo, local e condições de retirada do bem"),
        ("transferência", "documentos e providências para transferência"), ("responsabilidades", "obrigações, riscos e custos do arrematante"),
        ("estado dos bens", "venda no estado em que se encontram e inspeção prévia"), ("desistência", "consequências de desistência ou inadimplemento"),
        ("penalidades", "multas, sanções e perda de valores"), ("recursos", "canais, prazos e regras de impugnação ou recurso"),
        ("anexos", "anexos, catálogo e documentos complementares"), ("proteção de dados", "tratamento de dados pessoais e privacidade"),
        ("foro e legislação", "lei aplicável, foro e solução de controvérsias"),
    ];
    let enfoques = ["menção explícita", "regra principal", "prazo aplicável", "responsável indicado", "condição de validade", "documento exigido", "custo associado", "risco ao participante"];
    temas.iter().enumerate().flat_map(|(i, (tema, criterio))| enfoques.iter().enumerate().map(move |(j, enfoque)| Node {
        id: format!("edital_{i:02}_{j:02}"), parent: None,
        name: format!("{} — {}", tema, enfoque), kind: "classification".into(),
        instruction: format!("Classifique no trecho a existência de {} relativa a {}. Critério de análise: {}. Registre evidência literal quando houver.", enfoque, tema, criterio),
        categories: vec!["evidência explícita".into(), "sem evidência".into(), "ambíguo".into()], when: "always".into(), enabled: true, order: (i * enfoques.len() + j + 1) as u32,
    })).collect()
}
fn demo_text()->String { "CLÁUSULA 1 — A contratada deverá entregar o relatório financeiro até 30 de junho de 2026. João Silva será o responsável técnico.\n\nCLÁUSULA 2 — A contratante poderá solicitar esclarecimentos operacionais em até 10 dias após o recebimento.\n\nCLÁUSULA 3 — Este documento descreve o contexto comercial e não cria deveres adicionais.".into() }
fn count_tokens(s:&str)->usize { s.split_whitespace().count() }
fn split_text(text:&str, max:usize)->Vec<Chunk>{ let mut chunks=vec![]; let mut current=String::new(); for para in text.split("\n\n") { let candidate=if current.is_empty(){para.into()}else{format!("{current}\n\n{para}")}; if count_tokens(&candidate)>max && !current.is_empty(){let i=chunks.len();chunks.push(Chunk{index:i,text:current.clone(),tokens:count_tokens(&current),pages:"Texto extraído; página não disponibilizada".into()});current=para.into()}else{current=candidate} } if !current.trim().is_empty(){let i=chunks.len();chunks.push(Chunk{index:i,tokens:count_tokens(&current),text:current,pages:"Texto extraído; página não disponibilizada".into()})}; chunks }
fn initial_model()->Model { let text=demo_text(); Model{document:"demonstração integrada".into(),chunks:split_text(&text,140),nodes:example_nodes(),results:vec![],execution:Execution{state:"idle".into(),current:0,finished:0,limit:3,mode:"SIMULADO · tokenizador por palavras".into(),event:"Pronto para executar a bateria de exemplo".into()}} }
fn validate(nodes:&[Node])->Result<(),String>{ let ids:std::collections::HashSet<_>=nodes.iter().map(|n|n.id.as_str()).collect(); for n in nodes {if n.id.trim().is_empty()||n.name.trim().is_empty()||n.instruction.trim().is_empty(){return Err("Identificador, nome e instrução são obrigatórios.".into())}if n.kind=="classification"&&(n.categories.is_empty()||n.categories.iter().any(|x|x.trim().is_empty())){return Err(format!("Categorias inválidas em {}.",n.name))}if let Some(p)=&n.parent{if !ids.contains(p.as_str()){return Err(format!("Pai inexistente: {p}"))}}} for n in nodes {let mut seen=vec![n.id.as_str()];let mut p=n.parent.as_deref();while let Some(id)=p{if seen.contains(&id){return Err("A árvore não pode conter ciclos.".into())}seen.push(id);p=nodes.iter().find(|x|x.id==id).and_then(|x|x.parent.as_deref())}}Ok(())}
fn result_for(chunk:usize,node:&Node,text:&str)->ResultRow { let low=text.to_lowercase(); let yes=low.contains("deverá")||low.contains("devera")||low.contains("obrig")||low.contains("até")||low.contains(" em "); let mut answer=match node.id.as_str(){"obligation"=>if yes{"sim"}else{"não"},"deadline"=>if low.contains("até")||low.contains("dia")||low.contains("junho"){"sim"}else{"não"},"owner"=>if low.contains("joão")||low.contains("responsável"){"sim"}else{"não"},"type"=>if low.contains("financeir"){"financeira"}else if low.contains("operacion"){"operacional"}else{"outra"},"deadline_type"=>if low.contains("junho"){"data fixa"}else if low.contains("dias"){"período relativo"}else{"outro"},_=>""}.to_string(); let evidence: String=if low.contains("30 de junho"){"até 30 de junho de 2026"}else if low.contains("10 dias"){"em até 10 dias"}else if low.contains("joão silva"){"João Silva será o responsável técnico"}else if low.contains("deverá"){"A contratada deverá entregar o relatório financeiro"}else{""}.into(); if node.id.starts_with("edital_") { let hit = ["edital", "leilão", "lance", "arremat", "pagamento", "lote", "caixa"].iter().any(|word| low.contains(word)); answer = if hit { "evidência explícita" } else { "sem evidência" }.into(); } ResultRow{chunk,node:node.id.clone(),state:"done".into(),answer:answer.clone(),reason:if evidence.is_empty(){format!("Classificação simulada: {answer}.")}else{format!("Conclusão simulada: {answer}.")},evidence_found:!evidence.is_empty()&&text.contains(&evidence),evidence,duration_ms:650,attempts:1,error:String::new()} }
fn applicable(n:&Node, rows:&HashMap<String,ResultRow>)->String { if !n.enabled{return "disabled".into()} let Some(parent)=&n.parent else{return "run".into()}; let Some(r)=rows.get(parent) else{return "blocked".into()}; if r.state!="done" {return "blocked".into()} if n.when=="always"||n.when=="success"||n.when=="yes"&&r.answer=="sim"||n.when=="no"&&r.answer=="não"||n.when==r.answer {"run".into()}else{"na".into()} }
async fn run(app: App) {
    loop {
        let (chunk, nodes, limit, state) = { let m = app.model.read().await; (m.chunks.get(m.execution.current).cloned(), m.nodes.clone(), m.execution.limit, m.execution.state.clone()) };
        if matches!(state.as_str(), "cancelled" | "paused" | "completed") { break; }
        let Some(chunk) = chunk else { let mut m = app.model.write().await; m.execution.state = "completed".into(); m.execution.event = "Execução concluída — resultados persistidos".into(); break; };
        let mut finished: HashMap<String, ResultRow> = HashMap::new();
        loop {
            let ready: Vec<_> = nodes.iter().filter(|n| !finished.contains_key(&n.id) && applicable(n, &finished) == "run").cloned().collect();
            let pending: Vec<_> = nodes.iter().filter(|n| !finished.contains_key(&n.id)).cloned().collect();
            for n in pending { let st = applicable(&n, &finished); if matches!(st.as_str(), "na" | "disabled") { finished.insert(n.id.clone(), ResultRow { chunk: chunk.index, node: n.id.clone(), state: st, answer: String::new(), reason: String::new(), evidence: String::new(), evidence_found: false, duration_ms: 0, attempts: 0, error: String::new() }); } }
            if ready.is_empty() { break; }
            let mut tasks = JoinSet::new();
            for node in ready { let text = chunk.text.clone(); let index = chunk.index; tasks.spawn(async move { sleep(Duration::from_millis(650)).await; result_for(index, &node, &text) }); if tasks.len() >= limit.max(1) { if let Some(Ok(row)) = tasks.join_next().await { finished.insert(row.node.clone(), row); } } }
            while let Some(Ok(row)) = tasks.join_next().await { finished.insert(row.node.clone(), row); }
            app.model.write().await.execution.event = format!("Trecho {}: nós paralelos concluídos", chunk.index + 1);
        }
        let mut m = app.model.write().await; m.results.retain(|r| r.chunk != chunk.index); m.results.extend(finished.into_values()); m.execution.finished += 1; m.execution.current += 1; m.execution.event = format!("Trecho {} finalizado; preparando o próximo", chunk.index + 1); persist(&app.db, &m);
    }
}
fn persist(db:&Arc<Mutex<Connection>>,m:&Model){if let Ok(db)=db.lock(){let _=db.execute("INSERT INTO executions (snapshot, state) VALUES (?1,?2)",params![serde_json::to_string(m).unwrap_or_default(),m.execution.state]);}}
fn restore_model(db:&Arc<Mutex<Connection>>)->Model{db.lock().ok().and_then(|db|db.query_row("SELECT snapshot FROM executions ORDER BY id DESC LIMIT 1",[],|row|row.get::<_,String>(0)).optional().ok().flatten()).and_then(|snapshot|serde_json::from_str(&snapshot).ok()).unwrap_or_else(initial_model)}
async fn health()->&'static str{"ok\n"} async fn html()->Html<&'static str>{Html(APP_HTML)}
fn extract_pdf_text(body:&[u8])->Result<String,String>{let nonce=SystemTime::now().duration_since(UNIX_EPOCH).map_err(|_|"Relógio indisponível")?.as_nanos();let path=env::temp_dir().join(format!("laya-import-{nonce}.pdf"));fs::write(&path,body).map_err(|e|format!("Não foi possível preparar o PDF: {e}"))?;let output=Command::new("pdftotext").args(["-enc","UTF-8",path.to_string_lossy().as_ref(),"-"]).output();let _=fs::remove_file(&path);let output=output.map_err(|e|format!("Extrator de PDF indisponível: {e}"))?;if !output.status.success(){return Err(String::from_utf8_lossy(&output.stderr).trim().to_string())}String::from_utf8(output.stdout).map_err(|_|"O texto extraído não está em UTF-8 válido".into())}
async fn state(State(app):State<App>)->Json<Model>{Json(app.model.read().await.clone())}
async fn load_edital_battery(State(app):State<App>)->Json<Model>{let mut m=app.model.write().await;m.nodes=edital_battery();m.results.clear();m.execution.current=0;m.execution.finished=0;m.execution.state="idle".into();m.execution.event="Bateria de 200 classificações de edital carregada".into();persist(&app.db,&m);Json(m.clone())}
async fn save_nodes(State(app):State<App>,Json(input):Json<NodesInput>)->Result<Json<Model>,(StatusCode,Json<ErrorBody>)>{validate(&input.nodes).map_err(|e|(StatusCode::UNPROCESSABLE_ENTITY,Json(ErrorBody{error:e})))?;let mut m=app.model.write().await;m.nodes=input.nodes;persist(&app.db,&m);Ok(Json(m.clone()))}
async fn control(State(app):State<App>,Path(action):Path<String>)->Result<Json<Model>,(StatusCode,Json<ErrorBody>)>{let start;{let mut m=app.model.write().await;match action.as_str(){"start"|"resume"=>{if m.execution.current>=m.chunks.len(){m.execution.current=0;m.execution.finished=0;m.results.clear()}m.execution.state="running".into();m.execution.event="Agendando nós independentes em paralelo".into();start=true},"pause"=>{m.execution.state="paused".into();m.execution.event="Pausa solicitada: chamadas atuais podem concluir".into();start=false},"cancel"=>{m.execution.state="cancelled".into();m.execution.event="Cancelado: resultados concluídos foram preservados".into();start=false},_=>return Err((StatusCode::NOT_FOUND,Json(ErrorBody{error:"Ação inválida".into()})))} }if start{tokio::spawn(run(app.clone()));}Ok(Json(app.model.read().await.clone()))}
async fn import_pdf(State(app):State<App>,headers:HeaderMap,body:Bytes)->Result<Json<Model>,(StatusCode,Json<ErrorBody>)>{let name=headers.get("x-filename").and_then(|h|h.to_str().ok()).unwrap_or("documento.pdf");let text=extract_pdf_text(&body).map_err(|_|(StatusCode::UNPROCESSABLE_ENTITY,Json(ErrorBody{error:"Não foi possível extrair texto do PDF. OCR não é suportado nesta versão.".into()})))?;if text.trim().is_empty(){return Err((StatusCode::UNPROCESSABLE_ENTITY,Json(ErrorBody{error:"O PDF não contém texto extraível. OCR está fora do escopo.".into()})))}let mut m=app.model.write().await;m.document=name.into();m.chunks=split_text(&text,140);m.results.clear();m.execution.current=0;m.execution.finished=0;m.execution.state="idle".into();m.execution.event="PDF importado; revise os trechos antes de iniciar".into();persist(&app.db,&m);Ok(Json(m.clone()))}
#[tokio::main] async fn main(){let path=env::var("APP_DATABASE_URL").unwrap_or_else(|_|"data/laya-pdf-analyzer.db".into());if let Some(p)=std::path::Path::new(&path).parent(){let _=std::fs::create_dir_all(p);};let connection=Connection::open(path).expect("SQLite indisponível");connection.execute_batch("CREATE TABLE IF NOT EXISTS executions(id INTEGER PRIMARY KEY, snapshot TEXT NOT NULL, state TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);").expect("schema SQLite");let db=Arc::new(Mutex::new(connection));let app=App{model:Arc::new(RwLock::new(restore_model(&db))),db};let host=env::var("APP_HOST").unwrap_or_else(|_|"127.0.0.1".into());let port=env::var("APP_PORT").unwrap_or_else(|_|"8082".into());let router=Router::new().route("/",get(html)).route("/health",get(health)).route("/api/state",get(state)).route("/api/nodes",post(save_nodes)).route("/api/battery/edital-200",post(load_edital_battery)).route("/api/execution/{action}",post(control)).route("/api/import",post(import_pdf)).with_state(app);let addr=format!("{host}:{port}");println!("Laya PDF Analyzer: http://{addr}");axum::serve(tokio::net::TcpListener::bind(addr).await.unwrap(),router).await.unwrap()}
#[cfg(test)] mod tests {use super::*;#[test]fn includes_final_chunk(){let c=split_text("um dois\n\ntrês quatro",3);assert_eq!(c.len(),2);assert_eq!(c[1].text,"três quatro")}#[test]fn tree_rejects_cycles(){let mut n=example_nodes();n[0].parent=Some("deadline".into());assert!(validate(&n).is_err())}#[test]fn child_condition(){let r=ResultRow{chunk:0,node:"obligation".into(),state:"done".into(),answer:"não".into(),reason:"".into(),evidence:"".into(),evidence_found:false,duration_ms:0,attempts:0,error:"".into()};let mut rows=HashMap::new();rows.insert("obligation".into(),r);assert_eq!(applicable(&example_nodes()[1],&rows),"na")}#[test]fn edital_battery_has_200_valid_nodes(){let n=edital_battery();assert_eq!(n.len(),200);assert!(validate(&n).is_ok())}}
